[tool.poetry]
name = "saiph"
version = "0.1.0"
description = ""
authors = ["Julien Petot <julien.petot@yahoo.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pandas = "^1.3.3"
sklearn = "^0.0"
matplotlib = "^3.4.3"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
