[tool.poetry]
name = "saiph"
version = "0.1.0"
description = ""
authors = ["Zineb Bennis", "Julien Petot <julien@octopize-md.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
pandas = "^1.3.3"
sklearn = "^0.0"
matplotlib = "^3.4.3"
numpy = "^1.21.2"
scipy = "^1.7.1"

[tool.poetry.dev-dependencies]
Sphinx = "^4.2.0"
ipykernel = "^6.4.1"
sphinx-rtd-theme = "^1.0.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
