name: "Check PR ci"

on: pull_request

jobs:
  saiph-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Install dependencies
      run: uv sync --extra matplotlib --extra dev --extra doc

    - name: Typecheck
      run: just typecheck

    - name: Lint
      run: just lint

    - name: Build docs
      run: just docs

    - name: Run tests
      run: just test
