name: "Check PR ci"

on: pull_request

jobs:
  saiph-ci:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Load cached Poetry installation
      uses: actions/cache@v3
      with:
        path: ~/.local  # the path depends on the OS
        key: poetry-1  # increment to reset cache

    # will not install if it's already there (see previous cache step)
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true
        virtualenvs-path: ~/.venv


    # install deps (use cache if poetry.lock did not change)
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root --extras "matplotlib"

    - name: Install app
      run: poetry install --no-interaction

    - name: Typecheck
      run: make typecheck

    - name: Lint
      run: make lint

    - name: Build docs
      run: make docs

    - name: Run tests
      run: make test
